tool.matcolor.name=Material Color Tool
tool.matcolor.desc=Enables coloring of individual materials on a model.

tool.matcolor.0=Mouse Wheel Up/Down: Select target material, Primary: Apply color, Secondary: Reset color, Reload: Copy color

tool.matcolor.color=Color
tool.matcolor.lines=Lines displayed
